version: "3"

services:

  database:
    image: mysql:8
    environment:
        MYSQL_DATABASE: spring_social
        MYSQL_USER: plee
        MYSQL_PASSWORD: plee
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./database/spring_db/:/var/lib/mysql"
    ports:
      - "3309:3306"
    restart: always
    container_name: plee_mysql
    networks:
      - backend-network

  spring-boot:
    build: ./backend_spring/
      #context: ./backend_spring  ## 현재 폴더의 backend_spring 밑에 Dockerfile 실행
      #dockerfile: Dockerfile
    image: plee_auth
    ports:
      - "8080:8080"
    container_name: plee_auth
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://plee_mysql:3309/spring_social?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: plee
      SPRING_DATASOURCE_PASSWORD: plee
    networks:
      - backend-network

networks:
  backend-network: