version: "3.7"
services:
  database:
    container_name: database
    image: mysql:8
    volumes:
      - ./database/spring_db/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=database_name
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    restart: always
    
  application:
    build: ./backend_spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/database_name?testdbautoReconnect=true&failOverReadOnly=false&maxReconnects=10
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - database
    links: 
      - database:database
    restart: always